---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: "curiefense"
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: redis-hl
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: "curiefense"
    spec:
      containers:
      {{ if regexMatch ".*/.*:" .Values.global.images.redis }}
      {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
      - image: {{ .Values.global.images.redis }}
      {{ else }}
      - image: {{ .Values.global.images.redis }}:{{ .Values.global.settings.docker_tag }}
      {{ end }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis-tcp
        livenessProbe:
          tcpSocket:
            port: redis-tcp
        volumeMounts:
        - mountPath: /data
          name: persistent-redis
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
          limits:
            memory: "8Gi"
            cpu: "2000m"
          requests:
            memory: "4Gi"
            cpu: {{ .Values.global.requests.cpu.redis }}
      restartPolicy: Always
      serviceAccountName: ""
{{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: persistent-redis
    spec:
      storageClassName: {{ .Values.global.storage.storage_class_name }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.global.storage.redis_storage_size }}
