apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: uiserver
    app.kubernetes.io/part-of: "curiefense"
  name: uiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uiserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uiserver
        app.kubernetes.io/part-of: "curiefense"
    spec:
      containers:
      - name: uiserver
      {{ if regexMatch ".*/.*:" .Values.global.images.uiserver }}
      {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
        image: {{ .Values.global.images.uiserver }}
      {{ else }}
        image: {{ .Values.global.images.uiserver }}:{{ .Values.global.settings.docker_tag }}
      {{ end }}
        ports:
        - containerPort: 80
          name: uiserver-http
        livenessProbe:
          httpGet:
            path: /
            port: uiserver-http
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "900m"
          requests:
            memory: "10Mi"
            cpu: {{ .Values.global.requests.cpu.uiserver }}
      restartPolicy: Always
      imagePullSecrets:
        {{- .Values.global.imagePullSecrets | toYaml | nindent 8  }}
      serviceAccountName: ""
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
